-- Bypass mode is removed: Reservations cover booking tickets without an online payment, and
-- a free order still completes without Mollie.
-- No longer run (the table #__ticketstation_mollie is removed since 2.26.0): ALTER TABLE ... DROP COLUMN `bypass_mode`
